language: python
python:
  - "2.7"
  - "3.6"
  - "3.8"
  - "pypy"
  - "pypy3"
install:
  - pip install pipenv
  - pipenv install --dev
script:
  - pipenv run mamba
after_success:
  - pipenv run coverage report
